export const ROUTES = {
  home: "/home",
  browse: "/browse",
  search: "/search",
  discover: "/discover",
  newHot: "/new-hot",
  favorites: "/favorites",
  login: "/login",
  signup: "/signup",
  who: "/who",
  profile: "/profile",
  subscription: "/subscription",
  paymentSuccess: "/subscription/payment/success",
  paymentFail: "/subscription/payment/fail",
  admin: "/admin",
  movie: (id: number | string) => `/movie/${id}`,
  tv: (id: number | string) => `/tv/${id}`,
  person: (id: number | string) => `/person/${id}`,
  category: (type: string, category: string) => `/category/${type}/${category}`,
  genre: (genreId: number | string) => `/category/genre/${genreId}`,
  player: (type: "movie" | "tv", id: number | string) => `/player/${type}/${id}`,
  playerMovie: (id: number | string) => `/player/${id}`,
  playerTv: (id: number | string, season = 1, episode = 1) =>
    `/player/tv/${id}?season=${season}&episode=${episode}`,
} as const;
